<?php
/**
 * Plugin Name: Embold - Notice Suppression
 * Description: Automatically generated by Embold WordPress Tweaks to suppress notices early.
 */

defined('ABSPATH') || exit;

(function () {
    // 1. Check Constants (Highest Priority)
    // Priority: EMBOLD_SUPPRESS_LOGS (new) -> WPH_SUPPRESS_TEXTDOMAIN_NOTICES (legacy)
    if (defined('EMBOLD_SUPPRESS_LOGS') && !EMBOLD_SUPPRESS_LOGS) {
        return; // Explicitly disabled via new constant
    }
    if (defined('WPH_SUPPRESS_TEXTDOMAIN_NOTICES') && !WPH_SUPPRESS_TEXTDOMAIN_NOTICES) {
        return; // Explicitly disabled via legacy constant (backwards compatibility)
    }

    // 2. Check Database Option
    // We access the DB directly because this runs before the main plugin is loaded.
    // Default to TRUE if option is missing (matches main plugin logic).
    $all_opts = get_option('embold_tweaks_options', []);
    $suppress = isset($all_opts['suppress_notices']) ? (bool) $all_opts['suppress_notices'] : true;

    if (!$suppress) {
        return;
    }

    // --- LOGIC ---

    // Suppress deprecated notices
    error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);

    $strings_to_check = [
        '_load_textdomain_just_in_time',
        'Translation loading',
        'automatic_feed_links',
        'wp_deregister_script',
        'wp_register_script',
        'wp_enqueue_script',
        'Scripts and styles should not be registered or enqueued until the',
    ];

    // Merge custom strings
    // Merge custom strings from constant first (highest priority)
    if (defined('EMBOLD_SUPPRESS_LOGS_EXTRA')) {
        $const_val = constant('EMBOLD_SUPPRESS_LOGS_EXTRA');
        if (is_array($const_val)) {
            $strings_to_check = array_merge($strings_to_check, array_filter(array_map('trim', $const_val)));
        } elseif (!empty($const_val)) {
            // Support newline-separated or single string
            $custom = preg_split('/[\r\n]+/', (string) $const_val);
            if (is_array($custom)) {
                $strings_to_check = array_merge($strings_to_check, array_filter(array_map('trim', $custom)));
            }
        }
    }

    // Merge custom strings from option (second priority)
    if (!empty($all_opts['suppress_notice_extra_strings'])) {
        $custom = preg_split('/[\r\n]+/', $all_opts['suppress_notice_extra_strings']);
        if (is_array($custom)) {
            $strings_to_check = array_merge($strings_to_check, array_filter(array_map('trim', $custom)));
        }
    }

    add_filter('doing_it_wrong_trigger_error', function ($trigger, $function_name, $message, $version) use ($strings_to_check) {
        foreach ($strings_to_check as $s) {
            if (empty($s))
                continue;
            if ($function_name === $s || strpos($message, $s) !== false) {
                return false;
            }
        }
        return $trigger;
    }, 10, 4);
})();