<?php
/**
 * Plugin Name: Embold - Notice Suppression
 * Description: Automatically generated by Embold WordPress Tweaks to suppress notices early.
 */

// phpcs:disable WordPress.PHP.DevelopmentFunctions.prevent_path_disclosure_error_reporting, WordPress.PHP.DiscouragedPHPFunctions.runtime_configuration_error_reporting, WordPress.PHP.DevelopmentFunctions.error_log_set_error_handler

defined( 'ABSPATH' ) || exit;

( function () {
	// 1. Check Constants (Highest Priority)
	// Priority: EMBOLD_SUPPRESS_LOGS (new) -> WPH_SUPPRESS_TEXTDOMAIN_NOTICES (legacy)
	if ( defined( 'EMBOLD_SUPPRESS_LOGS' ) && ! EMBOLD_SUPPRESS_LOGS ) {
		return; // Explicitly disabled via new constant
	}
	if ( defined( 'WPH_SUPPRESS_TEXTDOMAIN_NOTICES' ) && ! WPH_SUPPRESS_TEXTDOMAIN_NOTICES ) {
		return; // Explicitly disabled via legacy constant (backwards compatibility)
	}

	// 2. Check Database Option
	// We access the DB directly because this runs before the main plugin is loaded.
	// Default to TRUE if option is missing (matches main plugin logic).
	$all_opts = get_option( 'embold_tweaks_options', [] );
	$suppress = isset( $all_opts['suppress_notices'] ) ? (bool) $all_opts['suppress_notices'] : true;

	if ( ! $suppress ) {
		return;
	}

	// --- LOGIC ---

	// Suppress deprecated notices
	error_reporting( E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED );

	$strings_to_check = [
		'_load_textdomain_just_in_time',
		'Translation loading',
		'automatic_feed_links',
		'wp_deregister_script',
		'wp_register_script',
		'wp_enqueue_script',
		'Scripts and styles should not be registered or enqueued until the',
	];

	// Merge custom strings
	// Merge custom strings from constant first (highest priority)
	if ( defined( 'EMBOLD_SUPPRESS_LOGS_EXTRA' ) ) {
		$const_val = constant( 'EMBOLD_SUPPRESS_LOGS_EXTRA' );
		if ( is_array( $const_val ) ) {
			$strings_to_check = array_merge( $strings_to_check, array_filter( array_map( 'trim', $const_val ) ) );
		} elseif ( ! empty( $const_val ) ) {
			// Support newline-separated or single string
			$custom = preg_split( '/[\r\n]+/', (string) $const_val );
			if ( is_array( $custom ) ) {
				$strings_to_check = array_merge( $strings_to_check, array_filter( array_map( 'trim', $custom ) ) );
			}
		}
	}

	// Merge custom strings from option (second priority)
	if ( ! empty( $all_opts['suppress_notice_extra_strings'] ) ) {
		$custom = preg_split( '/[\r\n]+/', $all_opts['suppress_notice_extra_strings'] );
		if ( is_array( $custom ) ) {
			$strings_to_check = array_merge( $strings_to_check, array_filter( array_map( 'trim', $custom ) ) );
		}
	}

	add_filter(
		'doing_it_wrong_trigger_error',
		function ( $trigger, $function_name, $message, $version ) use ( $strings_to_check ) {
			foreach ( $strings_to_check as $s ) {
				if ( empty( $s ) ) {
					continue;
				}
				if ( $function_name === $s || strpos( $message, $s ) !== false ) {
					return false;
				}
			}
			return $trigger;
		},
		10,
		4
	);

	// --- ERROR HANDLER ---
	// Suppress PHP errors (Warnings, Notices, etc.) from debug.log if they match suppression strings.
	// This prevents noisy plugins from filling up debug.log unnecessarily.
	set_error_handler(
		function ( $errno, $errstr, $errfile, $errline ) use ( $strings_to_check ) {
			// Only filter E_WARNING, E_USER_WARNING, E_NOTICE, E_USER_NOTICE, E_DEPRECATED, E_USER_DEPRECATED
			// Let E_ERROR, E_PARSE, E_FATAL pass through (too dangerous to suppress).
			$filterable_errors = E_WARNING | E_USER_WARNING | E_NOTICE | E_USER_NOTICE | E_DEPRECATED | E_USER_DEPRECATED | E_STRICT;

			if ( ! ( $errno & $filterable_errors ) ) {
				// Not a filterable error; pass to default handler.
				return false;
			}

			// Check if the error message matches any suppression strings.
			foreach ( $strings_to_check as $s ) {
				if ( empty( $s ) ) {
					continue;
				}
				if ( strpos( $errstr, $s ) !== false ) {
					// Suppress this error (don't log it).
					return true;
				}
			}

			// Not suppressed; pass to default handler.
			return false;
		}
	);
} )();
