name: WordPress Plugin Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch:

jobs:
  wordpress-plugin-release:
    uses: emboldagency/.github/.github/workflows/wordpress-plugin-release.yml@master
    with:
      tag: ${{ github.ref_name }}
