name: WordPress Plugin Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]" # IMPORTANT: This should match the tag_pattern input below
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
        description: 'Release tag (e.g., 1.0.0 or v1.0.0)'
      fix:
        required: false
        type: boolean
        default: false
        description: 'Set to true to update files, false to only check'

jobs:
  wordpress-plugin-release:
    uses: emboldagency/.github/.github/workflows/wordpress-plugin-release.yml@master
    with:
      tag: ${{ github.event.inputs.tag || github.ref_name }}
      fix: ${{ github.event.inputs.fix || false }}
      tag_pattern: '[0-9]+\.[0-9]+\.[0-9]+' # IMPORTANT: This should match the on.push.tags pattern above