name: WordPress Plugin Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]" # IMPORTANT: This should match the tag_pattern input below
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
        description: 'Release tag (e.g., `1.0.0`)'
      version_sync_mode:
        required: false
        type: string
        default: 'error'
        description: 'Enable to automatically update version numbers in plugin files to match the tag. If false, only check and fail on mismatch.'
jobs:
  wordpress-plugin-release:
    uses: emboldagency/.github/.github/workflows/wordpress-plugin-release.yml@master
    with:
      tag: ${{ github.event.inputs.tag || github.ref_name }}
      version_sync_mode: ${{ github.event.inputs.version_sync_mode || 'error' }}
      tag_pattern: '[0-9]+\.[0-9]+\.[0-9]+' # IMPORTANT: This should match the on.push.tags pattern above